name: Build Examples
run-name: ${{ github.actor }} is building platform-midi
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Build-And-Test:
    strategy:
      matrix:
        os: [ windows, osx-arm, osx-intel, linux ]
        include:
          - os: windows
            family: windows
            runner: windows-latest
            cores: 2
          - os: osx-arm
            family: osx
            runner: macos-latest
            cores: 3
          - os: osx-intel
            family: osx
            runner: macos-13
            cores: 4
          - os: linux
            family: linux
            runner: ubuntu-latest
            cores: 4
    runs-on:
      ${{ matrix.runner }}
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4.1.4
        with:
          submodules: recursive

      - name: Create a version file
        run: |
          printf "Commit: https://github.com/dylwhich/platform-midi/commit/$(git rev-parse HEAD) \nBuilt with ${{ matrix.os }} at: $(date)" >> version.txt

      - name: Install msys64 packages
        if: matrix.family == 'windows'
        run: |
          C:\msys64\usr\bin\bash -lc 'pacman --noconfirm -S base-devel gcc'

      - name: Install apt packages
        if: matrix.family == 'linux'
        run: |
          sudo apt-get install -y build-essential alsa-base libasound2 libasound2-dev

      - name: Compile Examples
        if: matrix.family == 'windows'
        run: |
          $env:path = $env:path.Insert($env:path.ToLower().IndexOf("c:\windows\system32"), "C:\msys64\mingw64\bin;C:\msys64\usr\bin;")
          make -j${{ matrix.cores}} examples

      - name: Compile Examples
        if: matrix.family != 'windows'
        run: |
          make -j${{ matrix.cores}} examples

      - name: Run Examples
        run: |
          ./examples/listdevs || echo "Failed to run listdevs!"
          ./examples/loopback || echo "Failed to run loopback!"
